debug: true
run-inserter: true
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=bank
    username: postgres
    password: revature
jpa:
  generate-ddl: true
  database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  show-sql: true
  hibernate:
    ddl-auto: create
    default_schema: bank


management:
  endpoints:
    web:
      exposure:
        include: "*" # do not enable all Actuator endpoints when deploying to prod (customer-facing)
